import { useCallback, useEffect, useMemo, useRef, useState } from 'react'
import * as THREE from 'three'
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js'

type Kind = '地面' | '墙体' | '门窗' | '楼梯' | '阳台' | '屋顶'
type Discipline = '建筑' | '结构' | '机电' | '场地'
type Item = { id: number; type: Kind; name: string; floor: number; x: number; y: number; z: number; width: number; height: number; depth: number; color: string; visible: boolean; discipline: Discipline }

const floors = [1, 2, 3]
const palette: { type: Kind; icon: string; discipline: Discipline }[] = [
  { type: '墙体', icon: '▥', discipline: '建筑' }, { type: '门窗', icon: '▣', discipline: '建筑' },
  { type: '楼梯', icon: '⌁', discipline: '结构' }, { type: '阳台', icon: '▱', discipline: '建筑' },
  { type: '屋顶', icon: '⌂', discipline: '建筑' }, { type: '地面', icon: '◫', discipline: '结构' },
]
const seed: Item[] = [
  { id: 1, type: '地面', name: '一层结构板', floor: 1, x: 0, y: 0, z: 0, width: 12, height: .18, depth: 8, color: '#dce9f7', visible: true, discipline: '结构' },
  { id: 2, type: '墙体', name: '北立面外墙', floor: 1, x: 0, y: 2.8, z: -3.8, width: 12, height: 5.6, depth: .22, color: '#f8fbff', visible: true, discipline: '建筑' },
  { id: 3, type: '墙体', name: '南立面外墙', floor: 1, x: 0, y: 2.8, z: 3.8, width: 12, height: 5.6, depth: .22, color: '#f8fbff', visible: true, discipline: '建筑' },
  { id: 4, type: '墙体', name: '东立面外墙', floor: 1, x: 5.9, y: 2.8, z: 0, width: .22, height: 5.6, depth: 7.6, color: '#f8fbff', visible: true, discipline: '建筑' },
  { id: 5, type: '墙体', name: '西立面外墙', floor: 1, x: -5.9, y: 2.8, z: 0, width: .22, height: 5.6, depth: 7.6, color: '#f8fbff', visible: true, discipline: '建筑' },
  { id: 6, type: '门窗', name: '落地窗-01', floor: 1, x: 2.2, y: 1.8, z: -3.64, width: 2.4, height: 2.8, depth: .12, color: '#86d8f2', visible: true, discipline: '建筑' },
  { id: 7, type: '门窗', name: '入户门', floor: 1, x: -1.8, y: 1.3, z: 3.62, width: 1.5, height: 2.6, depth: .12, color: '#b88f67', visible: true, discipline: '建筑' },
  { id: 8, type: '阳台', name: '客厅阳台', floor: 1, x: 1.8, y: 1.2, z: 4.35, width: 4.8, height: .24, depth: 1.6, color: '#c9e5f4', visible: true, discipline: '建筑' },
  { id: 9, type: '楼梯', name: '主楼梯', floor: 1, x: -3.5, y: .9, z: -1.6, width: 2.2, height: 2.8, depth: 1.2, color: '#c8d4e1', visible: true, discipline: '结构' },
  { id: 10, type: '屋顶', name: '平屋顶', floor: 1, x: 0, y: 5.6, z: 0, width: 12.2, height: .28, depth: 7.8, color: '#dbe5f1', visible: true, discipline: '建筑' },
  { id: 11, type: '地面', name: '二层结构板', floor: 2, x: 0, y: 5.8, z: 0, width: 12, height: .2, depth: 8, color: '#dce9f7', visible: true, discipline: '结构' },
  { id: 12, type: '墙体', name: '二层南墙', floor: 2, x: 0, y: 8.4, z: 3.8, width: 12, height: 5.6, depth: .18, color: '#f8fbff', visible: true, discipline: '建筑' },
  { id: 13, type: '门窗', name: '二层窗-101', floor: 2, x: 3.4, y: 8.1, z: -3.5, width: 2.2, height: 2.6, depth: .12, color: '#91ddf7', visible: true, discipline: '建筑' },
]

function Scene({ items, selectedId, onSelect, mode }: { items: Item[]; selectedId: number; onSelect: (id: number) => void; mode: '轴测' | '平面' }) {
  const host = useRef<HTMLDivElement>(null)
  useEffect(() => {
    const el = host.current; if (!el) return
    const scene = new THREE.Scene(); scene.background = new THREE.Color('#edf5ff')
    const camera = new THREE.PerspectiveCamera(42, el.clientWidth / el.clientHeight, .1, 200); camera.position.set(16, 14, 18)
    const renderer = new THREE.WebGLRenderer({ antialias: true }); renderer.setPixelRatio(Math.min(devicePixelRatio, 2)); renderer.setSize(el.clientWidth, el.clientHeight); renderer.shadowMap.enabled = true; el.replaceChildren(renderer.domElement)
    scene.add(new THREE.HemisphereLight('#fff', '#abc0d6', 1.8)); const light = new THREE.DirectionalLight('#fff4dd', 2.5); light.position.set(14, 20, 10); light.castShadow = true; scene.add(light)
    const ground = new THREE.Mesh(new THREE.PlaneGeometry(44, 44), new THREE.MeshStandardMaterial({ color: '#edf3fa', roughness: 1 })); ground.rotation.x = -Math.PI / 2; ground.position.y = -.12; ground.receiveShadow = true; scene.add(ground)
    const grid = new THREE.GridHelper(28, 28, '#bcd0e8', '#e0eaf6'); grid.position.y = -.05; scene.add(grid)
    const controls = new OrbitControls(camera, renderer.domElement); controls.enableDamping = true; controls.target.set(0, 3, 0); controls.maxPolarAngle = Math.PI / 2.05; controls.minDistance = 7; controls.maxDistance = 42
    if (mode === '平面') { camera.position.set(0, 24, .01); controls.target.set(0, 0, 0); controls.maxPolarAngle = Math.PI / 2; }
    const meshes: THREE.Mesh[] = []
    const add = (item: Item, geometry: THREE.BufferGeometry) => { const mat = new THREE.MeshStandardMaterial({ color: item.color, transparent: item.type === '门窗', opacity: item.type === '门窗' ? .78 : 1, roughness: item.type === '门窗' ? .1 : .55, metalness: item.type === '门窗' ? .3 : .04 }); const mesh = new THREE.Mesh(geometry, mat); mesh.position.set(item.x, item.y, item.z); mesh.castShadow = true; mesh.receiveShadow = true; mesh.userData.id = item.id; scene.add(mesh); meshes.push(mesh) }
    items.filter((item) => item.visible).forEach((item) => { if (item.type === '楼梯') { for (let i = 0; i < 8; i++) { const step = new THREE.Mesh(new THREE.BoxGeometry(1.8, .12, .52), new THREE.MeshStandardMaterial({ color: item.color, roughness: .65 })); step.position.set(item.x, item.y + i * .14, item.z + i * .38); step.userData.id = item.id; step.castShadow = true; scene.add(step); meshes.push(step) } } else add(item, new THREE.BoxGeometry(item.width, item.height, item.depth)) })
    const ray = new THREE.Raycaster(); const pointer = new THREE.Vector2(); const click = (event: MouseEvent) => { const rect = renderer.domElement.getBoundingClientRect(); pointer.x = (event.clientX - rect.left) / rect.width * 2 - 1; pointer.y = -(event.clientY - rect.top) / rect.height * 2 + 1; ray.setFromCamera(pointer, camera); const hit = ray.intersectObjects(meshes)[0]; if (hit?.object.userData.id) onSelect(Number(hit.object.userData.id)) }; renderer.domElement.addEventListener('click', click)
    let frame = 0; const animate = () => { frame = requestAnimationFrame(animate); controls.update(); meshes.forEach((mesh) => { const mat = mesh.material as THREE.MeshStandardMaterial; const active = mesh.userData.id === selectedId; mat.emissive.set(active ? '#7eaaff' : '#000'); mat.emissiveIntensity = active ? .3 : 0 }); renderer.render(scene, camera) }; animate()
    const resize = () => { camera.aspect = el.clientWidth / el.clientHeight; camera.updateProjectionMatrix(); renderer.setSize(el.clientWidth, el.clientHeight) }; window.addEventListener('resize', resize)
    return () => { cancelAnimationFrame(frame); window.removeEventListener('resize', resize); renderer.domElement.removeEventListener('click', click); controls.dispose(); renderer.dispose() }
  }, [items, mode, onSelect, selectedId])
  return <div ref={host} className="scene-root" />
}

function App() {
  const [items, setItems] = useState(seed); const [selectedId, setSelectedId] = useState(2); const [floor, setFloor] = useState(1); const [discipline, setDiscipline] = useState<Discipline>('建筑'); const [search, setSearch] = useState(''); const [mode, setMode] = useState<'轴测' | '平面'>('轴测'); const [saved, setSaved] = useState(false); const [history, setHistory] = useState<Item[][]>([]); const [future, setFuture] = useState<Item[][]>([])
  const selected = items.find((item) => item.id === selectedId) ?? items[0]
  const visible = useMemo(() => items.filter((item) => (item.floor === floor || item.type === '地面') && (discipline === '场地' || item.discipline === discipline) && item.name.includes(search)), [discipline, floor, items, search])
  const commit = useCallback((next: Item[]) => { setHistory((old) => [...old.slice(-19), items]); setFuture([]); setItems(next) }, [items])
  const update = <K extends keyof Item>(key: K, value: Item[K]) => commit(items.map((item) => item.id === selectedId ? { ...item, [key]: value } : item))
  const add = (type: Kind) => { const id = Date.now(); const y = type === '屋顶' ? 5.6 : type === '地面' ? 0 : type === '门窗' ? 1.8 : 2.5; const next: Item = { id, type, name: `${type}-${String(items.length + 1).padStart(2, '0')}`, floor, x: 0, y, z: 0, width: type === '门窗' ? 2 : type === '阳台' ? 4 : 3, height: type === '门窗' ? 2.5 : type === '阳台' ? .24 : type === '地面' ? .18 : 5, depth: type === '阳台' ? 1.4 : type === '门窗' ? .12 : .22, color: type === '门窗' ? '#8edcf6' : '#f7fbff', visible: true, discipline: type === '楼梯' || type === '地面' ? '结构' : '建筑' }; commit([...items, next]); setSelectedId(id) }
  const undo = () => { const previous = history.at(-1); if (!previous) return; setFuture((old) => [items, ...old]); setItems(previous); setHistory((old) => old.slice(0, -1)) }
  const redo = () => { const next = future[0]; if (!next) return; setHistory((old) => [...old, items]); setItems(next); setFuture((old) => old.slice(1)) }
  const exportModel = () => { const blob = new Blob([JSON.stringify({ name: '现代三层住宅方案', floors, elements: items }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(blob); link.download = 'building-model.json'; link.click(); URL.revokeObjectURL(link.href) }
  useEffect(() => { const key = (event: KeyboardEvent) => { if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'z') { event.preventDefault(); undo() } if ((event.metaKey || event.ctrlKey) && event.key.toLowerCase() === 'y') { event.preventDefault(); redo() } }; window.addEventListener('keydown', key); return () => window.removeEventListener('keydown', key) })
  return <div className="bim-shell">
    <aside className="sidebar left-sidebar"><div className="brand-box"><div className="brand-mark">B</div><div><strong>BuildCraft</strong><small>协同 BIM 工作台</small></div></div><div className="nav-group">{(['建筑', '结构', '机电', '场地'] as Discipline[]).map((tab) => <button key={tab} className={discipline === tab ? 'nav-tab active' : 'nav-tab'} onClick={() => setDiscipline(tab)}>{tab}</button>)}</div>
      <div className="panel-section"><div className="panel-title-row"><span>构件库</span><span className="status-pill">参数化</span></div><div className="palette-grid">{palette.filter((p) => discipline === '场地' || p.discipline === discipline).map((entry) => <button key={entry.type} className="palette-card" onClick={() => add(entry.type)}><span>{entry.icon}</span><strong>{entry.type}</strong></button>)}</div></div>
      <div className="panel-section tree-panel"><div className="panel-title-row"><span>模型树 · {visible.length}</span><button className="mini-button" onClick={() => setSearch('')}>⌕</button></div><input className="tree-search" value={search} onChange={(event) => setSearch(event.target.value)} placeholder="搜索构件 / 编号" /><div className="tree-list">{visible.map((item) => <button key={item.id} className={selectedId === item.id ? 'tree-item selected' : 'tree-item'} onClick={() => setSelectedId(item.id)}><span className="tree-icon">{item.type === '墙体' ? '▥' : item.type === '门窗' ? '▣' : item.type === '楼梯' ? '⌁' : item.type === '阳台' ? '▱' : item.type === '屋顶' ? '⌂' : '◫'}</span><span>{item.name}</span><small>{item.floor}F</small></button>)}</div></div></aside>
    <main className="viewer-panel"><header className="viewer-header"><div className="project-header-left"><div className="project-pill">协同项目</div><div><h1>现代三层住宅方案</h1><p>版本 v0.8.2 · 最后同步刚刚</p></div></div><div className="viewer-actions"><button className="soft-btn" onClick={undo} disabled={!history.length}>↶</button><button className="soft-btn" onClick={redo} disabled={!future.length}>↷</button><div className="divider" /><button className="primary-btn" onClick={() => { setSaved(true); window.setTimeout(() => setSaved(false), 1200) }}>{saved ? '已同步 ✓' : '保存并同步'}</button><button className="ghost-btn" onClick={exportModel}>导出 JSON</button></div></header>
      <div className="floor-bar">{floors.map((value) => <button key={value} className={floor === value ? 'floor-btn active' : 'floor-btn'} onClick={() => setFloor(value)}>{value}F <small>{value === 1 ? '首层' : value === 2 ? '标准层' : '屋顶层'}</small></button>)}<button className="floor-btn accent">+ 新楼层</button></div>
      <div className="canvas-wrap"><div className="toolbar-overlay"><div className="tool-group"><button className="tool-btn active">选择</button><button className="tool-btn">框选</button><button className="tool-btn">测量</button></div><div className="view-group"><button className={mode === '平面' ? 'tool-btn active' : 'tool-btn'} onClick={() => setMode('平面')}>平面</button><button className={mode === '轴测' ? 'tool-btn active' : 'tool-btn'} onClick={() => setMode('轴测')}>轴测</button></div></div><div className="view-hud"><span className="online-dot" />实时协同 <b>3 人在线</b><span className="hud-separator" />LOD 300 <span className="hud-separator" />阴影开启</div><Scene items={visible} selectedId={selectedId} onSelect={setSelectedId} mode={mode} /></div>
      <div className="status-row"><div className="status-item"><span className="online-dot" />云端已同步</div><div className="status-item">当前视图：{mode}</div><div className="status-item">单位：米</div><div className="status-item">已加载 {visible.length} / {items.length} 构件</div></div></main>
    <aside className="sidebar right-sidebar"><div className="panel-title-row big-row"><span>属性检查器</span><span className="status-pill">BIM 元素</span></div>{selected && <><div className="property-card"><div className="property-header"><h2>{selected.name}</h2><span>{selected.type}</span></div><label>构件名称<input value={selected.name} onChange={(event) => update('name', event.target.value)} /></label><div className="two-column"><label>楼层<select value={selected.floor} onChange={(event) => update('floor', Number(event.target.value))}>{floors.map((value) => <option key={value} value={value}>{value}F</option>)}</select></label><label>专业<select value={selected.discipline} onChange={(event) => update('discipline', event.target.value as Discipline)}>{['建筑', '结构', '机电', '场地'].map((value) => <option key={value}>{value}</option>)}</select></label></div><div className="section-caption">几何参数 · 单位 m</div><div className="two-column"><label>宽度 W<input type="number" value={selected.width} onChange={(event) => update('width', Number(event.target.value))} /></label><label>高度 H<input type="number" value={selected.height} onChange={(event) => update('height', Number(event.target.value))} /></label></div><div className="two-column"><label>深度 D<input type="number" value={selected.depth} onChange={(event) => update('depth', Number(event.target.value))} /></label><label>标高 Y<input type="number" value={selected.y} onChange={(event) => update('y', Number(event.target.value))} /></label></div><div className="two-column"><label>X<input type="number" value={selected.x} onChange={(event) => update('x', Number(event.target.value))} /></label><label>Z<input type="number" value={selected.z} onChange={(event) => update('z', Number(event.target.value))} /></label></div><label>材质颜色<div className="color-row"><span className="color-swatch" style={{ background: selected.color }} /><input value={selected.color} onChange={(event) => update('color', event.target.value)} /></div></label><button className={selected.visible ? 'switch active' : 'switch'} onClick={() => update('visible', !selected.visible)}>{selected.visible ? '● 可见' : '○ 已隐藏'}</button></div><div className="collab-card"><div className="panel-title-row narrow"><span>协同与审阅</span><span className="status-pill">3 条变更</span></div><div className="member-list"><div className="member-row"><span className="avatar avatar-blue">Z</span><div><strong>周娜</strong><small>结构审核 · 2分钟前</small></div><span className="tag green">已确认</span></div><div className="member-row"><span className="avatar avatar-purple">L</span><div><strong>李明</strong><small>机电协调 · 正在查看</small></div><span className="tag orange">待审核</span></div></div></div><div className="action-bar"><button className="soft-danger" onClick={() => { commit(items.filter((item) => item.id !== selected.id)); setSelectedId(items[0]?.id ?? 0) }}>删除</button><button className="primary-btn compact" onClick={() => add(selected.type)}>复制构件</button></div></>}</aside>
  </div>
}
export default App
